apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: zot2836fi-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zot2836fi-nodejs 
  name: zot2836fi-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: zot2836fi-nodejs 
